"""Add season episode columns for Netflix

Revision ID: 2ee4ed2b84a4
Revises: 4e8528666160
Create Date: 2026-03-01 10:56:31.220030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee4ed2b84a4'
down_revision: Union[str, None] = '4e8528666160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_videos', sa.Column('season', sa.Integer(), nullable=True))
    op.add_column('tracked_videos', sa.Column('episode', sa.Integer(), nullable=True))
    op.add_column('tracked_videos', sa.Column('episode_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_videos', 'episode_title')
    op.drop_column('tracked_videos', 'episode')
    op.drop_column('tracked_videos', 'season')
    # ### end Alembic commands ###
