"""add has_ukrainian column

Revision ID: 3e4e8ca7d1a4
Revises: d2705f429d58
Create Date: 2026-02-28 11:53:18.178927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e4e8ca7d1a4'
down_revision: Union[str, None] = 'd2705f429d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_videos', sa.Column('has_ukrainian', sa.Boolean(), nullable=True))
    op.alter_column('tracked_videos', 'subtitles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracked_videos', 'subtitles',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('tracked_videos', 'has_ukrainian')
    # ### end Alembic commands ###
