"""add duration_seconds to tracked_videos

Revision ID: bd0f591d96d7
Revises: d2705f429d58
Create Date: 2026-02-28 12:19:14.699122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0f591d96d7'
down_revision: Union[str, None] = 'd2705f429d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_videos', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_videos', 'duration_seconds')
    # ### end Alembic commands ###
