"""add tracked_videos table

Revision ID: d2705f429d58
Revises: a18867f8c5c0
Create Date: 2026-02-25 20:27:38.537104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2705f429d58'
down_revision: Union[str, None] = 'a18867f8c5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_videos',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('subtitles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tracked_at', sa.Float(), nullable=False),
    sa.Column('has_korean', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_videos_id'), 'tracked_videos', ['id'], unique=False)
    op.create_index(op.f('ix_tracked_videos_video_id'), 'tracked_videos', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_videos_video_id'), table_name='tracked_videos')
    op.drop_index(op.f('ix_tracked_videos_id'), table_name='tracked_videos')
    op.drop_table('tracked_videos')
    # ### end Alembic commands ###
